// Copyright 2025 The Android Open Source Project
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either expresso or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Auto-generated with: android/scripts/gen-entries.py --mode=funcargs android/android-emugl/host/libs/libOpenglRender/render_api.entries --output=android/android-emugl/host/include/OpenglRender/render_api_functions.h
// DO NOT EDIT THIS FILE

#ifndef RENDER_API_FUNCTIONS_H
#define RENDER_API_FUNCTIONS_H

#include "render-utils/RenderLib.h"

#define LIST_RENDER_API_FUNCTIONS(X) X(gfxstream::RenderLibPtr, initLibrary, (), ())

#endif  // RENDER_API_FUNCTIONS_H
