load("@protobuf//bazel:cc_proto_library.bzl", "cc_proto_library")
load("@protobuf//bazel:proto_library.bzl", "proto_library")
load("@rules_cc//cc:defs.bzl", "cc_binary", "cc_library", "cc_test", "objc_library")
load("//:build_variables.bzl", "GFXSTREAM_HOST_COPTS", "GFXSTREAM_HOST_DEFINES")

package(
    default_applicable_licenses = ["//:gfxstream_license"],
    default_visibility = ["//:gfxstream"],
)

proto_library(
    name = "gfxstream_backend_proto",
    srcs = [
        "virtio_gpu_context_snapshot.proto",
        "virtio_gpu_frontend_snapshot.proto",
        "virtio_gpu_resource_snapshot.proto",
        "virtio_gpu_ring_blob_snapshot.proto",
        "virtio_gpu_timelines_snapshot.proto",
    ],
    strip_import_prefix = "/host",
)

cc_proto_library(
    name = "gfxstream_backend_cc_proto",
    deps = [":gfxstream_backend_proto"],
)

cc_library(
    name = "gfxstream_backend_headers",
    hdrs = [
        "include/gfxstream/virtio-gpu-gfxstream-renderer.h",
        "include/gfxstream/virtio-gpu-gfxstream-renderer-unstable.h",
        "include/render-utils/MediaNative.h",
        "include/render-utils/RenderChannel.h",
        "include/render-utils/RenderLib.h",
        "include/render-utils/Renderer.h",
        "include/render-utils/address_space_graphics_types.h",
        "include/render-utils/address_space_operations.h",
        "include/render-utils/display_operations.h",
        "include/render-utils/dma_device.h",
        "include/render-utils/gralloc_enums.h",
        "include/render-utils/logging_operations.h",
        "include/render-utils/render_api.h",
        "include/render-utils/render_api_functions.h",
        "include/render-utils/render_api_platform_types.h",
        "include/render-utils/renderer_enums.h",
        "include/render-utils/small_vector.h",
        "include/render-utils/snapshot_operations.h",
        "include/render-utils/stream.h",
        "include/render-utils/sync_device.h",
        "include/render-utils/virtio_gpu_ops.h",
        "include/render-utils/vm_operations.h",
        "include/render-utils/window_operations.h",
    ],
    copts = GFXSTREAM_HOST_COPTS,
    defines = GFXSTREAM_HOST_DEFINES,
    features = ["-parse_headers"],
    includes = ["include"],
    visibility = ["//visibility:public"],
    deps = [
        "//host/features:gfxstream_host_features",
    ],
)

cc_library(
    name = "gfxstream_host_headers",
    hdrs = [
        "buffer.h",
        "color_buffer.h",
        "compositor.h",
        "frame_buffer.h",
        "framework_formats.h",
        "gles_compat.h",
        "handle.h",
        "hwc2.h",
        "native_sub_window.h",
        "post_commands.h",
        "post_worker.h",
        "readback_worker.h",
        "stale_ptr_registry.h",
        "vsync_thread.h",
    ],
    copts = GFXSTREAM_HOST_COPTS,
    defines = GFXSTREAM_HOST_DEFINES,
    includes = ["."],
    deps = [
        ":gfxstream_backend_headers",
        "//common/base:gfxstream_common_base",
        "//common/logging:gfxstream_common_logging",
        "//host/common:gfxstream_host_common",
        "//host/features:gfxstream_host_features",
        "//host/snapshot:gfxstream_host_snapshot",
        "//third_party/opengl:gfxstream_egl_headers",
        "//third_party/opengl:gfxstream_gles2_headers",
        "//third_party/opengl:gfxstream_gles3_headers",
        "//third_party/vulkan:gfxstream_vulkan_headers",
        "//third_party/xcb",
    ],
)

objc_library(
    name = "gfxstream_backend_static-darwin",
    srcs = [
        "gles_compat.h",
        "native_sub_window.h",
        "native_sub_window_cocoa.mm",
    ],
    copts = GFXSTREAM_HOST_COPTS + [
        "-Wno-deprecated-declarations",
        "-std=c++20",
    ],
    defines = GFXSTREAM_HOST_DEFINES,
    sdk_frameworks = [
        "AppKit",
        "QuartzCore",
        "IOSurface",
    ],
    target_compatible_with = [
        "@platforms//os:macos",
    ],
    deps = [
        ":gfxstream_backend_headers",
        "//third_party/opengl:gfxstream_egl_headers",
    ],
)

cc_library(
    name = "gfxstream_backend_static",
    srcs = [
        "buffer.cpp",
        "channel_stream.cpp",
        "color_buffer.cpp",
        "frame_buffer.cpp",
        "hwc2.cpp",
        "post_worker.cpp",
        "post_worker_gl.cpp",
        "read_buffer.cpp",
        "render_channel_impl.cpp",
        "render_control.cpp",
        "render_lib_impl.cpp",
        "render_thread.cpp",
        "render_thread_info.cpp",
        "render_window.cpp",
        "renderer_impl.cpp",
        "ring_stream.cpp",
        "sync_thread.cpp",
        "virtio_gpu_context.cpp",
        "virtio_gpu_frontend.cpp",
        "virtio_gpu_pipe.cpp",
        "virtio_gpu_resource.cpp",
        "virtio_gpu_ring_blob.cpp",
        "virtio_gpu_timelines.cpp",
        "vsync_thread.cpp",
    ] + select({
        "@platforms//os:macos": [],
        "@platforms//os:windows": [
            "native_sub_window_win32.cpp",
        ],
        "@platforms//os:linux": [
            "native_sub_window_x11.cpp",
        ],
        "//conditions:default": [],
    }),
    hdrs = [
        "buffer.h",
        "channel_stream.h",
        "color_buffer.h",
        "compositor.h",
        "frame_buffer.h",
        "framework_formats.h",
        "gles_compat.h",
        "handle.h",
        "hwc2.h",
        "native_sub_window.h",
        "post_commands.h",
        "post_worker.h",
        "post_worker_gl.h",
        "read_buffer.h",
        "readback_worker.h",
        "render_channel_impl.h",
        "render_control.h",
        "render_lib_impl.h",
        "render_thread.h",
        "render_thread_info.h",
        "render_window.h",
        "renderer_impl.h",
        "ring_stream.h",
        "stale_ptr_registry.h",
        "sync_thread.h",
        "virtgpu_gfxstream_protocol.h",
        "virtio_gpu.h",
        "virtio_gpu_context.h",
        "virtio_gpu_format_utils.h",
        "virtio_gpu_frontend.h",
        "virtio_gpu_pipe.h",
        "virtio_gpu_resource.h",
        "virtio_gpu_ring_blob.h",
        "virtio_gpu_timelines.h",
        "vsync_thread.h",
    ],
    copts = GFXSTREAM_HOST_COPTS + [
        "-Wno-extern-c-compat",
        "-Wno-return-type-c-linkage",
        "-Wno-unused-private-field",
    ],
    defines = GFXSTREAM_HOST_DEFINES + ["QEMU_NEXT"],
    includes = [
        ".",
        "gl",
    ],
    linkstatic = True,
    visibility = ["//visibility:public"],
    deps = [
        ":gfxstream_backend_cc_proto",
        ":gfxstream_backend_headers",
        ":gfxstream_host_headers",
        "//common/base:gfxstream_common_base",
        "//common/logging:gfxstream_common_logging",
        "//host/address_space:gfxstream_host_address_space",
        "//host/common:gfxstream_host_common",
        "//host/compressed_textures:gfxstream_host_compressed_textures",
        "//host/decoder_common:gfxstream_host_decoder_common",
        "//host/features:gfxstream_host_features",
        "//host/gl:gfxstream_opengl_server",
        "//host/gl/OpenGLESDispatch:gfxstream_host_openglesdispatch",
        "//host/gl/OpenGLESDispatch:gfxstream_host_openglesdispatch_headers",
        "//host/gl/gles1_dec:gfxstream_gles1_dec",
        "//host/gl/gles2_dec:gfxstream_gles2_dec",
        "//host/gl/glestranslator/common:gfxstream_glestranslator_common_headers",
        "//host/gl/glestranslator/egl:gfxstream_glestranslator_egl_translator",
        "//host/gl/glestranslator/gles_cm:gles_cm_translator_static",
        "//host/iostream:gfxstream_host_iostream",
        "//host/library:gfxstream_host_library",
        "//host/renderControl_dec",
        "//host/renderdoc:gfxstream_host_renderdoc",
        "//host/snapshot:gfxstream_host_snapshot",
        "//host/tracing:gfxstream_host_tracing",
        "//host/vulkan:gfxstream_vulkan_server",
        "//third_party/drm:gfxstream_drm_headers",
        "//third_party/opengl:gfxstream_egl_headers",
        "//third_party/opengl:gfxstream_gles2_headers",
        "//third_party/opengl:gfxstream_gles3_headers",
        "//third_party/vulkan:gfxstream_vulkan_headers",
        "//third_party/xcb",
        "@protobuf",
        "@protobuf//src/google/protobuf/io",
    ] + select({
        "@platforms//os:macos": [
            ":gfxstream_backend_static-darwin",
        ],
        "//conditions:default": [],
    }),
)

cc_library(
    name = "gfxstream_backend_shared",
    srcs = [
        "render_api.cpp",
        "virtio_gpu_gfxstream_renderer.cpp",
    ],
    copts = GFXSTREAM_HOST_COPTS + [
        "-Wno-extern-c-compat",
        "-Wno-return-type-c-linkage",
    ],
    defines = GFXSTREAM_HOST_DEFINES,
    linkstatic = True,
    visibility = ["//visibility:public"],
    deps = [
        ":gfxstream_backend_cc_proto",
        ":gfxstream_backend_headers",
        ":gfxstream_backend_static",
        ":gfxstream_host_headers",
        "//common/base:gfxstream_common_base",
        "//common/logging:gfxstream_common_logging",
        "//common/utils:gfxstream_common_utils",
        "//host/address_space:gfxstream_host_address_space",
        "//host/features:gfxstream_host_features",
        "//host/tracing:gfxstream_host_tracing",
        "//host/vulkan:gfxstream_vulkan_server",
    ],
)

cc_binary(
    name = "gfxstream_backend",
    srcs = [
        "render_api.cpp",
        "virtio_gpu_gfxstream_renderer.cpp",
    ],
    copts = GFXSTREAM_HOST_COPTS,
    defines = GFXSTREAM_HOST_DEFINES,
    linkshared = True,
    visibility = ["//visibility:public"],
    deps = [
        ":gfxstream_backend_cc_proto",
        ":gfxstream_backend_headers",
        ":gfxstream_backend_static",
        ":gfxstream_host_headers",
        "//common/base:gfxstream_common_base",
        "//common/logging:gfxstream_common_logging",
        "//common/utils:gfxstream_common_utils",
        "//host/address_space:gfxstream_host_address_space",
        "//host/features:gfxstream_host_features",
        "//host/tracing:gfxstream_host_tracing",
        "//host/vulkan:gfxstream_vulkan_server",
    ],
)

cc_test(
    name = "gfxstream_framebuffer_tests",
    srcs = [
        "frame_buffer_unittest.cpp",
    ],
    copts = GFXSTREAM_HOST_COPTS,
    deps = [
        ":gfxstream_backend_static",
        "//common/base:gfxstream_common_base",
        "//common/testenv:graphics_test_environment_support",
        "//host/common:gfxstream_host_common",
        "//host/features:gfxstream_host_features",
        "//host/testlibs/oswindow:gfxstream_oswindow_test_support",
        "//host/testlibs/support:gfxstream_host_testing_support",
        "@com_google_googletest//:gtest",
        "@com_google_googletest//:gtest_main",
    ],
)

cc_test(
    name = "gfxstream_vsyncthread_tests",
    srcs = [
        "vsync_thread_unittest.cpp",
    ],
    copts = GFXSTREAM_HOST_COPTS,
    deps = [
        ":gfxstream_backend_static",
        "//host/testlibs/support:gfxstream_host_testing_support",
        "@com_google_googletest//:gtest",
        "@com_google_googletest//:gtest_main",
    ],
)
