// Copyright 2025 The Android Open Source Project
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either expresso or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Auto-generated with: ./scripts/gen-entries.py --mode=funcargs host/gl/OpenGLESDispatch/gles32_only.entries --output=host/gl/OpenGLESDispatch/gles32_only_functions.h
// DO NOT EDIT THIS FILE

#ifndef GLES32_ONLY_FUNCTIONS_H
#define GLES32_ONLY_FUNCTIONS_H

#include <GLES/gl.h>
#include <GLES3/gl3.h>
#include <GLES3/gl32.h>

// The definitions of `GLDEBUGPROC` and `GLDEBUGPROCKHR` are unfortunately both
// protected by the same `ifndef GL_KHR_debug` which will cause files which
// include both to only have one of the two type definitions. The definition of
// GLDEBUGPROC is also different between desktop GL and GLES 3.2. Define our own
// typedefs here to work around this issue.
typedef void (*GFXSTREAM_GLES32_GLDEBUGPROC)(GLenum source,GLenum type,GLuint id,GLenum severity,GLsizei length,const GLchar *message,const void *userParam);

#define LIST_GLES32_ONLY_FUNCTIONS(X) \
  X(void, glDebugMessageControl, (GLenum source, GLenum type, GLenum severity, GLsizei count, const GLuint * ids, GLboolean enabled), (source, type, severity, count, ids, enabled)) \
  X(void, glDebugMessageInsert, (GLenum source, GLenum type, GLuint id, GLenum severity, GLsizei length, const GLchar * buf), (source, type, id, severity, length, buf)) \
  X(void, glDebugMessageCallback, (GFXSTREAM_GLES32_GLDEBUGPROC callback, const void * userParam), (callback, userParam)) \
  X(GLuint, glGetDebugMessageLog, (GLuint count, GLsizei bufSize, GLenum * sources, GLenum * types, GLuint * ids, GLenum * severities, GLsizei * lengths, GLchar * messageLog), (count, bufSize, sources, types, ids, severities, lengths, messageLog)) \
  X(void, glPushDebugGroup, (GLenum source, GLuint id, GLsizei length, const GLchar* message), (source, id, length, message)) \
  X(void, glPopDebugGroup, (), ()) \


#endif  // GLES32_ONLY_FUNCTIONS_H
