// Copyright 2025 The Android Open Source Project
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either expresso or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Auto-generated with: ./scripts/gen-entries.py --mode=funcargs host/gl/OpenGLESDispatch/gles3_extensions.entries --output=host/gl/OpenGLESDispatch/include/OpenGLESDispatch/gles3_extensions_functions.h
// DO NOT EDIT THIS FILE

#ifndef GLES3_EXTENSIONS_FUNCTIONS_H
#define GLES3_EXTENSIONS_FUNCTIONS_H

#include <GLES3/gl3.h>
#define LIST_GLES3_EXTENSIONS_FUNCTIONS(X) \
  X(void, glVertexAttribIPointerWithDataSize, (GLuint indx, GLint size, GLenum type, GLsizei stride, const GLvoid* ptr, GLsizei dataSize), (indx, size, type, stride, ptr, dataSize)) \
  X(void, glPrimitiveRestartIndex, (GLuint index), (index)) \
  X(void, glTexBufferOES, (GLenum target, GLenum internalformat, GLuint buffer), (target, internalformat, buffer)) \
  X(void, glTexBufferRangeOES, (GLenum target, GLenum internalformat, GLuint buffer, GLintptr offset, GLsizeiptr size), (target, internalformat, buffer, offset, size)) \
  X(void, glTexBufferEXT, (GLenum target, GLenum internalformat, GLuint buffer), (target, internalformat, buffer)) \
  X(void, glTexBufferRangeEXT, (GLenum target, GLenum internalformat, GLuint buffer, GLintptr offset, GLsizeiptr size), (target, internalformat, buffer, offset, size)) \
  X(void, glEnableiEXT, (GLenum cap, GLuint index), (cap, index)) \
  X(void, glDisableiEXT, (GLenum cap, GLuint index), (cap, index)) \
  X(void, glBlendEquationiEXT, (GLuint buf, GLenum mode), (buf, mode)) \
  X(void, glBlendEquationSeparateiEXT, (GLuint buf, GLenum modeRGB, GLenum modeAlpha), (buf, modeRGB, modeAlpha)) \
  X(void, glBlendFunciEXT, (GLuint buf, GLenum sfactor, GLenum dfactor), (buf, sfactor, dfactor)) \
  X(void, glBlendFuncSeparateiEXT, (GLuint buf, GLenum srcRGB, GLenum dstRGB, GLenum srcAlpha, GLenum dstAlpha), (buf, srcRGB, dstRGB, srcAlpha, dstAlpha)) \
  X(void, glColorMaskiEXT, (GLuint buf, GLboolean red, GLboolean green, GLboolean blue, GLboolean alpha), (buf, red, green, blue, alpha)) \
  X(GLboolean, glIsEnablediEXT, (GLenum cap, GLuint index), (cap, index)) \


#endif  // GLES3_EXTENSIONS_FUNCTIONS_H
