// Copyright 2025 The Android Open Source Project
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either expresso or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Generated Code - DO NOT EDIT !!
// generated by './scripts/generate-apigen-sources.sh'
#ifndef __renderControl_client_ftable_t_h
#define __renderControl_client_ftable_t_h


static const struct _renderControl_funcs_by_name {
	const char *name;
	void *proc;
} renderControl_funcs_by_name[] = {
	{"rcGetRendererVersion", (void*)rcGetRendererVersion},
	{"rcGetEGLVersion", (void*)rcGetEGLVersion},
	{"rcQueryEGLString", (void*)rcQueryEGLString},
	{"rcGetGLString", (void*)rcGetGLString},
	{"rcGetNumConfigs", (void*)rcGetNumConfigs},
	{"rcGetConfigs", (void*)rcGetConfigs},
	{"rcChooseConfig", (void*)rcChooseConfig},
	{"rcGetFBParam", (void*)rcGetFBParam},
	{"rcCreateContext", (void*)rcCreateContext},
	{"rcDestroyContext", (void*)rcDestroyContext},
	{"rcCreateWindowSurface", (void*)rcCreateWindowSurface},
	{"rcDestroyWindowSurface", (void*)rcDestroyWindowSurface},
	{"rcCreateColorBuffer", (void*)rcCreateColorBuffer},
	{"rcOpenColorBuffer", (void*)rcOpenColorBuffer},
	{"rcCloseColorBuffer", (void*)rcCloseColorBuffer},
	{"rcSetWindowColorBuffer", (void*)rcSetWindowColorBuffer},
	{"rcFlushWindowColorBuffer", (void*)rcFlushWindowColorBuffer},
	{"rcMakeCurrent", (void*)rcMakeCurrent},
	{"rcFBPost", (void*)rcFBPost},
	{"rcFBSetSwapInterval", (void*)rcFBSetSwapInterval},
	{"rcBindTexture", (void*)rcBindTexture},
	{"rcBindRenderbuffer", (void*)rcBindRenderbuffer},
	{"rcColorBufferCacheFlush", (void*)rcColorBufferCacheFlush},
	{"rcReadColorBuffer", (void*)rcReadColorBuffer},
	{"rcUpdateColorBuffer", (void*)rcUpdateColorBuffer},
	{"rcOpenColorBuffer2", (void*)rcOpenColorBuffer2},
	{"rcCreateClientImage", (void*)rcCreateClientImage},
	{"rcDestroyClientImage", (void*)rcDestroyClientImage},
	{"rcSelectChecksumHelper", (void*)rcSelectChecksumHelper},
	{"rcCreateSyncKHR", (void*)rcCreateSyncKHR},
	{"rcClientWaitSyncKHR", (void*)rcClientWaitSyncKHR},
	{"rcFlushWindowColorBufferAsync", (void*)rcFlushWindowColorBufferAsync},
	{"rcDestroySyncKHR", (void*)rcDestroySyncKHR},
	{"rcSetPuid", (void*)rcSetPuid},
	{"rcUpdateColorBufferDMA", (void*)rcUpdateColorBufferDMA},
	{"rcCreateColorBufferDMA", (void*)rcCreateColorBufferDMA},
	{"rcWaitSyncKHR", (void*)rcWaitSyncKHR},
	{"rcCompose", (void*)rcCompose},
	{"rcCreateDisplay", (void*)rcCreateDisplay},
	{"rcDestroyDisplay", (void*)rcDestroyDisplay},
	{"rcSetDisplayColorBuffer", (void*)rcSetDisplayColorBuffer},
	{"rcGetDisplayColorBuffer", (void*)rcGetDisplayColorBuffer},
	{"rcGetColorBufferDisplay", (void*)rcGetColorBufferDisplay},
	{"rcGetDisplayPose", (void*)rcGetDisplayPose},
	{"rcSetDisplayPose", (void*)rcSetDisplayPose},
	{"rcSetColorBufferVulkanMode", (void*)rcSetColorBufferVulkanMode},
	{"rcReadColorBufferYUV", (void*)rcReadColorBufferYUV},
	{"rcIsSyncSignaled", (void*)rcIsSyncSignaled},
	{"rcCreateColorBufferWithHandle", (void*)rcCreateColorBufferWithHandle},
	{"rcCreateBuffer", (void*)rcCreateBuffer},
	{"rcCloseBuffer", (void*)rcCloseBuffer},
	{"rcSetColorBufferVulkanMode2", (void*)rcSetColorBufferVulkanMode2},
	{"rcMapGpaToBufferHandle", (void*)rcMapGpaToBufferHandle},
	{"rcCreateBuffer2", (void*)rcCreateBuffer2},
	{"rcMapGpaToBufferHandle2", (void*)rcMapGpaToBufferHandle2},
	{"rcFlushWindowColorBufferAsyncWithFrameNumber", (void*)rcFlushWindowColorBufferAsyncWithFrameNumber},
	{"rcSetTracingForPuid", (void*)rcSetTracingForPuid},
	{"rcMakeCurrentAsync", (void*)rcMakeCurrentAsync},
	{"rcComposeAsync", (void*)rcComposeAsync},
	{"rcDestroySyncKHRAsync", (void*)rcDestroySyncKHRAsync},
	{"rcComposeWithoutPost", (void*)rcComposeWithoutPost},
	{"rcComposeAsyncWithoutPost", (void*)rcComposeAsyncWithoutPost},
	{"rcCreateDisplayById", (void*)rcCreateDisplayById},
	{"rcSetDisplayPoseDpi", (void*)rcSetDisplayPoseDpi},
	{"rcReadColorBufferDMA", (void*)rcReadColorBufferDMA},
	{"rcGetFBDisplayConfigsCount", (void*)rcGetFBDisplayConfigsCount},
	{"rcGetFBDisplayConfigsParam", (void*)rcGetFBDisplayConfigsParam},
	{"rcGetFBDisplayActiveConfig", (void*)rcGetFBDisplayActiveConfig},
	{"rcSetProcessMetadata", (void*)rcSetProcessMetadata},
	{"rcGetHostExtensionsString", (void*)rcGetHostExtensionsString},
	{"rcGetDisplayColorTransform", (void*)rcGetDisplayColorTransform},
	{"rcSetDisplayColorTransform", (void*)rcSetDisplayColorTransform},
};
static const int renderControl_num_funcs = sizeof(renderControl_funcs_by_name) / sizeof(struct _renderControl_funcs_by_name);


#endif
