name: Gfxstream Postsubmit

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */3 * * *'

jobs:
  postsubmit-populate-bazel-cache:
    runs-on: ubuntu-22.04
    steps:
    - name: Free disk space
      uses: jlumbroso/free-disk-space@v1.3.1
      with:
        tool-cache: true
    - name: Checkout repository
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1
    - name: Install bazel
      run: sudo bash toolchain/bazel/install_bazel.sh
    - name: Install toolchain dependencies
      run: sudo bash toolchain/bazel/install_toolchain_dependencies.sh
    - name: Load cache config
      run: cat .config/cache-config.env >> $GITHUB_ENV
    - name: Mount bazel cache
      uses: actions/cache@v5
      with:
        path: "~/bazel-disk-cache"
        key: ${{ format('{0}-{1}-bazel-disk-cache-{2}-{3}-{4}-{5}', runner.os, runner.arch, env.CACHE_VERSION, github.ref_name, github.sha, github.event_name) }}
        restore-keys: |
          ${{ github.event_name == 'push' && format('{0}-{1}-bazel-disk-cache-{2}-{3}-{4}-', runner.os, runner.arch, env.CACHE_VERSION, github.ref_name, github.sha) || '' }}
          ${{ github.event_name == 'push' && format('{0}-{1}-bazel-disk-cache-{2}-{3}-', runner.os, runner.arch, env.CACHE_VERSION, github.ref_name) || '' }}
          ${{ github.event_name == 'push' && format('{0}-{1}-bazel-disk-cache-{2}-main-', runner.os, runner.arch, env.CACHE_VERSION) || '' }}
          ${{ github.event_name == 'push' && format('{0}-{1}-bazel-disk-cache-{2}-', runner.os, runner.arch, env.CACHE_VERSION) || '' }}
    - name: Build
      run: |
        bazel build ... \
          --disk_cache=$HOME/bazel-disk-cache \
          --graphics_drivers=gles_angle_vulkan_swiftshader \
          --verbose_failures
  postsubmit-populate-bazel-cache-arm:
    runs-on: ubuntu-22.04-arm
    steps:
    - name: Free disk space
      uses: jlumbroso/free-disk-space@v1.3.1
      with:
        tool-cache: true
    - name: Checkout repository
      uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1
    - name: Install bazel
      run: sudo bash toolchain/bazel/install_bazel.sh
    - name: Install toolchain dependencies
      run: sudo bash toolchain/bazel/install_toolchain_dependencies.sh
    - name: Load cache config
      run: cat .config/cache-config.env >> $GITHUB_ENV
    - name: Mount bazel cache
      uses: actions/cache@v5
      with:
        path: "~/bazel-disk-cache"
        key: ${{ format('{0}-{1}-bazel-disk-cache-{2}-debian-package-{3}-{4}-{5}', runner.os, runner.arch, env.CACHE_VERSION, github.ref_name, github.sha, github.event_name) }}
        restore-keys: |
          ${{ github.event_name == 'push' && format('{0}-{1}-bazel-disk-cache-{2}-debian-package-{3}-', runner.os, runner.arch, env.CACHE_VERSION, github.ref_name) || '' }}
          ${{ github.event_name == 'push' && format('{0}-{1}-bazel-disk-cache-{2}-debian-package-main-', runner.os, runner.arch, env.CACHE_VERSION) || '' }}
          ${{ github.event_name == 'push' && format('{0}-{1}-bazel-disk-cache-{2}-debian-package-', runner.os, runner.arch, env.CACHE_VERSION) || '' }}
    - name: Build
      run: |
        bazel build ... \
          --disk_cache=$HOME/bazel-disk-cache \
          --graphics_drivers=gles_angle_vulkan_swiftshader \
          --verbose_failures
